config/routes.rb
Rails.application.routes.draw do  
  # resources :builds
  get 'webhook_actions/:id/delete' => 'webhook_actions#destroy', as: 'webhook_actions_delete'
  resources :webhook_actions do
    resources :builds, only: [:create, :show, :index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/build.rb
class Build < ApplicationRecord
  belongs_to :webhook_action
end

app/models/webhook_action.rb
class WebhookAction < ApplicationRecord
  has_many :builds, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  http_basic_authenticate_with name: ENV["username"], password: ENV["password"]
  protect_from_forgery with: :null_session
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  before_action :set_build, only: %i[ show edit update destroy ]

  # GET /builds or /builds.json
  def index
    @webhook_action = WebhookAction.find(params[:webhook_action_id])
    @builds = @webhook_action.builds
  end

  # GET /builds/1 or /builds/1.json
  def show
  end

  # POST /builds or /builds.json
  def create
    @build = Build.new(build_params)
    @build.webhook_action_id = @webhook_action.id
    if @build.save
      @@webhook_action.script.split("\r\n").each do |cmd|
        Rails.logger.info "Exc: #{cmd}"
        system(cmd)
      end
      
      render :show, status: :created
    else
      render json: @build.errors, status: :unprocessable_entity
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_build
      @webhook_action = WebhookAction.find(params[:webhook_action_id])
      @build = Build.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def build_params
      params.require(:build).permit(:webhook_action, :webhook_action_id, :build_info)
    end
end

app/controllers/webhook_actions_controller.rb
class WebhookActionsController < ApplicationController
  before_action :set_webhook_action, only: %i[ show edit update destroy ]

  # GET /webhook_actions or /webhook_actions.json
  def index
    @webhook_actions = WebhookAction.all
  end

  # GET /webhook_actions/1 or /webhook_actions/1.json
  def show
  end

  # GET /webhook_actions/new
  def new
    @webhook_action = WebhookAction.new
  end

  # GET /webhook_actions/1/edit
  def edit
  end

  # POST /webhook_actions or /webhook_actions.json
  def create
    @webhook_action = WebhookAction.new(webhook_action_params)

    respond_to do |format|
      if @webhook_action.save
        format.html { redirect_to webhook_action_url(@webhook_action), notice: "Webhook action was successfully created." }
        format.json { render :show, status: :created, location: @webhook_action }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @webhook_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /webhook_actions/1 or /webhook_actions/1.json
  def update
    respond_to do |format|
      if @webhook_action.update(webhook_action_params)
        format.html { redirect_to webhook_action_url(@webhook_action), notice: "Webhook action was successfully updated." }
        format.json { render :show, status: :ok, location: @webhook_action }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @webhook_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /webhook_actions/1 or /webhook_actions/1.json
  def destroy
    @webhook_action.destroy

    respond_to do |format|
      format.html { redirect_to webhook_actions_url, notice: "Webhook action was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_webhook_action
      @webhook_action = WebhookAction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def webhook_action_params
      params.require(:webhook_action).permit(:title, :script_type, :script)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/builds_helper.rb
module BuildsHelper
end

app/helpers/webhook_actions_helper.rb
module WebhookActionsHelper
end

app/views/builds/_form.html.erb
<%= form_with(model: build, local: true) do |form| %>
  <% if build.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(build.errors.count, "error") %> prohibited this build from being saved:</h2>

      <ul>
      <% build.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :webhook_action %>
    <%= form.text_field :webhook_action %>
  </div>

  <div class="field">
    <%= form.label :build_info %>
    <%= form.text_area :build_info %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/builds/edit.html.erb
<h1>Editing Build</h1>

<%= render 'form', build: @build %>

<%= link_to 'Show', @build %> |
<%= link_to 'Back', builds_path %>

app/views/builds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Builds</h1>

<table>
  <thead>
    <tr>
      <th>Webhook action</th>
      <th>Build info</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @builds.each do |build| %>
      <tr>
        <td><%= build.webhook_action_id %></td>
        <td><%= build.build_info %></td>
        <td><%= link_to 'Show', webhook_action_build_path(build.webhook_action_id,build) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/builds/new.html.erb
<h1>New Build</h1>

<%= render 'form', build: @build %>

<%= link_to 'Back', builds_path %>

app/views/builds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Webhook action:</strong>
  <%= @build.webhook_action_id %>
</p>

<p>
  <strong>Build info:</strong>
  <%= @build.build_info %>
</p>

<%= link_to 'Back', webhook_action_builds_path(@build.webhook_action_id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebhookActions</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/webhook_actions/_form.html.erb
<%= form_with(model: webhook_action, local: true) do |form| %>
  <% if webhook_action.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(webhook_action.errors.count, "error") %> prohibited this webhook_action from being saved:</h2>

      <ul>
      <% webhook_action.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :script_type %>
    <%= form.text_field :script_type %>
  </div>

  <div class="field">
    <%= form.label :script %>
    <%= form.text_area :script %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/webhook_actions/edit.html.erb
<h1>Editing Webhook Action</h1>

<%= render 'form', webhook_action: @webhook_action %>

<%= link_to 'Show', @webhook_action %> |
<%= link_to 'Back', webhook_actions_path %>

app/views/webhook_actions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Webhook Actions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Script type</th>
      <th>Script</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @webhook_actions.each do |webhook_action| %>
      <tr>
        <td><%= webhook_action.title %></td>
        <td><%= webhook_action.script_type %></td>
        <td><%= webhook_action.script %></td>
        <td><%= link_to 'Show', webhook_action %></td>
        <td><%= link_to 'Builds', webhook_action_builds_path(webhook_action) %></td>
        <td><%= link_to 'Edit', edit_webhook_action_path(webhook_action) %></td>
        <td>          
          <%= link_to 'Destroy', webhook_actions_delete_path(webhook_action), html_options: {"data-method": :delete} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Webhook Action', new_webhook_action_path %>

app/views/webhook_actions/new.html.erb
<h1>New Webhook Action</h1>

<%= render 'form', webhook_action: @webhook_action %>

<%= link_to 'Back', webhook_actions_path %>

app/views/webhook_actions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @webhook_action.title %>
</p>

<p>
  <strong>Script type:</strong>
  <%= @webhook_action.script_type %>
</p>

<p>
  <strong>Script:</strong>
  <%= @webhook_action.script %>
</p>

<%= link_to 'Edit', edit_webhook_action_path(@webhook_action) %> |
<%= link_to 'Back', webhook_actions_path %>